plugins:
  user_feedbacks_enabled:
    client: true
    default: true
  user_feedbacks_display_average_ratings_beside_username_on_post:
    client: true
    default: true
  user_feedbacks_display_average_ratings_on_profile:
    client: true
    default: true
  user_feedbacks_display_average_ratings_on_user_card:
    client: true
    default: true
  user_feedbacks_unique_per_topic:
    client: true
    default: true
    description: "Prevent users from leaving multiple feedbacks for the same user in the same topic"
